# Generated by Django 4.1.7 on 2023-03-06 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_footballteam_foundingyear_footballteam_nickname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footballteam',
            old_name='teamName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='footballteam',
            old_name='profesionalStatus',
            new_name='professionalStatus',
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField(default=-1)),
                ('age', models.IntegerField(default=-1)),
                ('rating', models.IntegerField(default=-1)),
                ('position', models.CharField(default='Substitute', max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.footballteam')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=-1)),
                ('nationality', models.CharField(max_length=100)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.footballteam')),
            ],
        ),
    ]
