# Generated by Django 4.1.7 on 2023-03-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_teamname_footballteam_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='license',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coach',
            name='yearsOfExperience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coach',
            name='age',
            field=models.IntegerField(),
        ),
    ]
