# Generated by Django 4.1.7 on 2023-03-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_coach_license_coach_yearsofexperience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='yearsOfExperience',
        ),
        migrations.AddField(
            model_name='coach',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
