# Generated by Django 4.1.7 on 2023-03-19 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_coach_yearsofexperience_coach_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('foundingYear', models.IntegerField()),
                ('nationality', models.CharField(max_length=100)),
                ('netWorth', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='api.footballteam'),
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
    ]
