# Generated by Django 4.1.7 on 2023-03-19 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sponsor_alter_player_team_delete_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Has',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealValue', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorNames', to='api.sponsor')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamNames', to='api.footballteam')),
            ],
        ),
    ]
