# Generated by Django 4.1.7 on 2023-03-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_has'),
    ]

    operations = [
        migrations.AlterField(
            model_name='has',
            name='dealValue',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='netWorth',
            field=models.IntegerField(max_length=100),
        ),
    ]
