# Generated by Django 4.1.7 on 2023-03-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_has_dealvalue_alter_sponsor_networth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='netWorth',
            field=models.IntegerField(),
        ),
    ]
